### PR TITLE
Watsonx.ai L4: Create lab for LangChain integration

### PR DESCRIPTION
**Pull request by jbukuts**
Relates to https://github.com/ibm-build-lab/VAD-VAR-Workshop/issues/293

Content changes:

- Created lab 203 for L4 LangChain integration
- Added reference to the README
- Changed final script from original lab into notebook

Code changes:

- N/A

Testing:

As a note the URLs referenced for notebooks will not currently work so import the local files or run them locally to test.

### CODE REVIEW

**Comment by maurelya** [comment]
@jbukuts This lab should be numbered 203.

L4-genai-01 1

**Comment by jbukuts** [comment]
> @jbukuts This lab should be numbered 203.
> 
> L4-genai-01 1

Thanks for pointing this out. Renumber everything to 203 👍

**Review by maurelya — APPROVED** [review]

**Comment by maurelya** [comment]
You'll need to create the Spanish files later.

**Review by krab7191 — APPROVED** [review]
Looks good. I'm having issues running it in the SVA cloud account environment, but it doesn't seem to be a problem with the lab itself.

**Comment by krab7191** [comment]
https://github.com/ibm-build-lab/VAD-VAR-Workshop/issues/324

**Pull request merged**
